volumes:
  fooocus-data:

services:
  app:
    build: .
    image: ghcr.io/lllyasviel/fooocus
    ports:
     - "7865:7865"
    environment:
      - CMDARGS=--listen
      - DATADIR=/data
      - FOOOCUS_DATA_DIR=/data
      - FOOOCUS_USER_DATA_DIR=/data
      - config_path=/data/config.txt
      - config_example_path=/data/config_modification_tutorial.txt
      - sorted_styles_path=/data/sorted_styles.json
      - path_checkpoints=/data/models/checkpoints/
      - path_loras=/data/models/loras/
      - path_embeddings=/data/models/embeddings/
      - path_vae=/data/models/vae/
      - path_vae_approx=/data/models/vae_approx/
      - path_upscale_models=/data/models/upscale_models/
      - path_inpaint=/data/models/inpaint/
      - path_controlnet=/data/models/controlnet/
      - path_clip_vision=/data/models/clip_vision/
      - path_fooocus_expansion=/data/models/prompt_expansion/fooocus_expansion/
      - path_safety_checker=/data/models/safety_checker/
      - path_sam=/data/models/sam/
      - path_outputs=/data/outputs/
      - temp_path=/data/cache/temp/
      - MANIFEST_CHECK=1
      - MANIFEST_STRICT=0
      - MANIFEST_CHECK_HASH=0
    volumes:
      - fooocus-data:/data
      #- ./models:/import/models   # Once you import files, you don't need to mount again.
      #- ./outputs:/import/outputs  # Once you import files, you don't need to mount again.
      #- ./manifest.json:/import/manifest.json  # Import a custom manifest
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [compute, utility]
